### ISSUE TITLE
Using someone else's backpack crashes the game

### ISSUE THREAD

**Issue by rlycx** [PetiAPocok/minetest_extended#2]
Trying to put an item in a slot in your backpack tab when you don't have a backback equipped crashes the game. 
Also, players who aren't wearing a backpack still have a backpack tab in their inventories when someone else on the server is wearing one.

**Comment by PetiAPocok** [comment]
Thanks for the report. I appreciate the feedback and I know that there are serious problems with the backpacks, that's the reason why I replaced them with void bags (in the development version). Until I release a new version I suggest avoid using the backpacks or use the development version of MEx (probably contains more surprise bugs).
