### ISSUE TITLE
Crafting guide should deal with items that have no recipe

### ISSUE THREAD

**Issue by mk-pmb** [PetiAPocok/minetest_extended#5]
Affected by upstream bug: https://github.com/minetest-mods/craftguide/issues/118

**Comment by PetiAPocok** [comment]
Thanks for mentioning. But that is a problem that isn't affecting my game.
You can modify my game, and put in any other mods that you like, but if that causes any problem for you, I'm sorry for the unpleasant experience but that is up to you to solve it.

**Comment by mk-pmb** [comment]
Well, the missing error handling is in the version of craftguide that ships with MTEx, so I thought you might be interested in tracking it, even though it only triggers with other mods added. It's ok if you don't, though.

**Comment by PetiAPocok** [comment]
I use to update the mods I use, so if they fix it in the future then everything is alright. If it will cause problems for me, then I will fix it. But again, thanks for mentioning.
